version: '3.8'

services:
  # ============================================
  # PostgreSQL Database (single instance on manager)
  # ============================================
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: logs_db
      POSTGRES_USER: logs_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - logmein-backend-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U logs_user -d logs_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    secrets:
      - db_password

  # ============================================
  # Backend - Flask API (replicated across workers)
  # ============================================
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY:-logmein}/backend:${TAG:-latest}
    environment:
      DB_HOST: db
      DB_NAME: logs_db
      DB_USER: logs_user
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_PORT: 5432
    networks:
      - logmein-backend-network
      - logmein-frontend-network
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 256M
          cpus: '0.50'
        reservations:
          memory: 128M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    secrets:
      - db_password
    depends_on:
      - db

  # ============================================
  # Frontend - Nginx (replicated, exposed)
  # ============================================
  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY:-logmein}/frontend:${TAG:-latest}
    ports:
      - "80:80"
    networks:
      - logmein-frontend-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.10'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local

networks:
  logmein-backend-network:
    driver: overlay
    encrypted: true
  logmein-frontend-network:
    driver: overlay
    encrypted: true

secrets:
  db_password:
    external: true
